////

    Copyright © 2019 Christian Kaltepoth
    Copyright © 2020 Copyright (c) 2020 Contributors to the Eclipse Foundation

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

////
== Appeals Process

As stated by the link:https://jakarta.ee/committees/specification/tckprocess/[TCK process,window=_blank], _Specifications are the sole source of truth and considered overruling to the TCK in all senses_. Therefore, during the implementation of a specification it can happen, that the implementing party is considering a test of this TCK as non-conform to the specification. To get this problem resolved, the implementing party can create a _challenge_ for the test.

To file a challenge, please create an issue in the link:https://github.com/eclipse-ee4j/mvc-tck/issues/[MVC TCK issue tracker,window=_blank} as described in the link:https://jakarta.ee/committees/specification/tckprocess#_filing_a_challenge[TCK process - Filing a challenge,window=_blank].