////

    Copyright © 2019 Christian Kaltepoth
    Copyright (c) 2020, 2025 Contributors to the Eclipse Foundation

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

////
== TCK Challenge and resolution process for **Jakarta MVC**

This specification allows for lazy consensus as a resolution path for TCK test challenges as described in the Jakarta EE TCK Process Guide.
For this specification, test challenges will be deemed accepted, 14 days from the date the test challenge issue is filed.
Please file your challenge in conformance with "Filing a Challenge" requirements in the TCK Process Guide.
If any specification team member determines that the challenge requires review it should be marked with the tag `challenge-review` and it will be resolved under the 'Active Resolution' process as described in the Jakarta EE TCK Process guide.
Generally, once a conversation occurs with a member of the committer team, the filer should consider that the challenge will follow the Active Resolution process.

In the event a challenge is approved under lazy consensus, any vendor implementation Compatibility Certification Request (CCR) that uses this challenge must include the issue ID along with the TCK details and test reporting statistics for this specification, regardless if the CCR is filed to this specification project issue tracker, or it is filed for any other specification project issue tracker. Failure to include this issue reference could result in CCR  approval delay.

Once a TCK revision, that includes the resolution of this challenge is released, it is no longer necessary to include any additional reference in your CCR.

This specification team tries to track issues as they are filed but feel free to reach out to us via mvc-dev@eclipse.org.
If that fails, you may escalate your issue to the Jakarta EE Platform Committer list jakartaee-platform-dev@eclipse.org.
If it is necessary to escalate further, you may request action following the Grievance process as described in the Eclipse Development Process, Handbook under Grievance Handling.
