////

    Copyright © 2019 Christian Kaltepoth
    Copyright (c) 2020, 2025 Contributors to the Eclipse Foundation

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

////
[[running_sig_tests]]
== Running the signature tests

The signature file bundled inside this TCK is created using the https://github.com/eclipse-ee4j/jakartaee-tck-tools/tree/master/tools/sigtest [SigTest Maven plugin]. The same plugin can be used to run a signature test to check for any incompatibilities. Let’s take a look how it can be done as a part of a Maven build. Note that there must be no dependency declared for this project besides the API artifact you wish to test.

Before running an actual test you need to obtain the signature file first. It is included inside the validation tck distribution artifacts subdirectory as vmvc-tck-sigtest-3.0.0.sigfile.

To actually run a signature test, the check goal of the sigtest-maven-plugin can be used. The TCK distribution sample/sigtest-pom.xml includes a sigtest profile that can be used to run the signature test.

Running it should produce the following output:

[source,sh]
```
[INFO] SignatureTest report
Base version: 3.0.0
Tested version: 3.0.0
Check mode: bin [throws removed]
Constant checking: on
```